package com.yahya.filmticket.model

import com.yahya.filmticket.R

object FakeFilmTicketDataSource {
    val dummyFilmTickets = listOf(
        FilmTicket(1, R.drawable.img_1, "Animal", 55000, "Arjun Singh (Ranbir Kapoor) mengalami transformasi yang luar biasa ketika ikatan dengan ayahnya, Balbir Singh (Anil Kapoor) mulai renggang, dan keinginannya untuk balas dendam semakin kuat."),
        FilmTicket(2, R.drawable.img_2, "Rumah Masa Depan", 50000, "Diangkat dari serial televisi dan serial novel yang amat populer di tahun 1980-an: Rumah Masa Depan karya Ali Shahab.Kali ini Sukri (Fedi Nuril) dan Surti (Laura Basuki) harus pulang ke kampung Cibeureum, karena Pak Musa (Cok Simbara), yaitu ayah Sukri, meninggal dunia. Namun setelah pemakaman, keluarga Sukri tidak bisa langsung kembali ke Jakarta, karena Bu Musa (Widyawati) dituduh terlibat kasus kriminal. Suasana keluarga makin tak menentu, karena “api dalam sekam” konflik lama yang terjadi antara Bu Musa dan Surti justru menjadi makin berkobar. Sedangkan kedua anak mereka, Bayu (Bima Azriel) dan Gerhana (Ciara Brosnan) mulai nyaman bertemu teman-teman baru, Cempaka (Maisha Kanna) dan Sangaji (Zayyan Sakha), dan bertualang mencoba membantu menyelesaikan masalah keluarga. Dapatkah konflik ibu mertua dan menantu terselesaikan demi kebahagiaan keluarga?"),
        FilmTicket(3, R.drawable.img_3, "Malam Para Jahanam", 50000, "Rendi (Harris Vriza) ditemani Martin (Zoul Pandjoul) dan Siska (Amel Carla) mengantar jenazah kakeknya ke sebuah desa dan terjebak teror dendam Malam Para Jahanam. Mereka ditolong Marni (Djenar Maesa Ayu) dan Dira (Aghniny Haque) yang bercerita tentang konflik berdarah antara kelompok Pemuda Rakyat berhaluan komunis dengan kelompok santri pimpinan Kyai Malik (Teddy Syach) di tahun 1965. Apakah mereka bisa melewati kutukan tiga malam jahanam mencekam itu?"),
        FilmTicket(4, R.drawable.img_4, "All Fun And Games", 55000, "Sebuah pisau terkutuk membawa musibah kepada remaja di wilayah Salem. Memaksa mereka untuk memainkan sebuah permainan masa kecil yang mengerikan. Tidak ada pemenang dan hanya berusaha untuk selamat."),
        FilmTicket(5, R.drawable.img_5, "Napoleon", 55000, "Berlatar tahun 1793, di masa era Revolusi Prancis terjadi. Napoleon akan berkisah tentang Jenderal Napoleon Bonaparte (Joaquin Phoenix) sosok ambisius, cerdas dan ahli strategi yang berani melawan koalisi negara-negara Eropa untuk memperluas kekuasaannya. Perjalanan kejayaan sang kaisar sampai hubungan cintanya bersama Josephine (Vanessa Kirby)."),
        FilmTicket(6, R.drawable.img_6, "Thanksgiving", 55000, "Setelah kerusuhan Black Friday berakhir dengan tragedi, seorang pembunuh misterius yang terinspirasi dari Thanksgiving meneror kota Plymouth, Massachusetts. Satu per satu korban terbunuh mengenaskan. Siapakah pembunuh misterius ini dan apakah motif di baliknya?"),
        FilmTicket(7, R.drawable.img, "Wonka", 55000, "Wonka akan berkisah tentang awal kehidupan Willy Wonka (Timothee Chalamet) sebelum dia menjadi pemilik dari pabrik coklat yang misterius dan terkenal. Perjuangan anak muda membuat coklat terenak di dunia dan dikenal oleh masyarakat luas."),
        FilmTicket(8, R.drawable.img_8, "172 Days", 50000, "172 hari yang indah untuk Zira (Yasmin Napper), dan berkesan sepanjang hidupnya. Menikah dengan putra ustadz legendaris Arifin Ilham, Amer Azzikra (Bryan Domani), yang telah membuat Zira menjadi pribadi yang lebih baik. Namun Amer pergi terlalu cepat. \"Aku ikhlas, namun aku rindu!\""),
        FilmTicket(9, R.drawable.img_9, "Gampang Cuan", 50000, "Di tengah kesulitan finansial keluarga yang tak kunjung usai, Sultan (Vino G Bastian) dan adik perempuannya, Bilqis (Anya Geraldine), harus mengatasi warisan utang mendiang ayah mereka sebesar 300 juta. Sultan mencoba berbagai pekerjaan, sementara Bilqis berusaha memahami dunia saham sebagai solusi untuk mengatasi utang tersebut. Namun, itu semua tidaklah mudah, dan mereka juga terus-terusan dirongrong Aji (Alzi Marker), si bungsu yang nekad datang ke Jakarta untuk minta dibiayai kuliah karena menganggap dirinya spesial dan satu-satunya harapan keluarga. Semua ini harus berhasil dilakukan tanpa sepengetahuan Mama (Meriam Bellina), yang punya penyakit jantung dan gampang stress."),
        FilmTicket(10, R.drawable.img_10, "Panggonan Wingit", 50000, "RAINA (Luna Maya) dan adiknya, FEY (Bianca Hello) pindah dari Jakarta ke Semarang untuk mengelola Hotel Ambar Mangun, sebuah hotel warisan ayah mereka yang tidak pernah mereka kunjungi sebelumnya dan selama ini dikelola oleh SUKTINI (Oce Permatasari) dan GARINTO (Budi Ros), nenek dan kakek mereka. Suatu malam Raina mendengar suara tangis dari lantai tiga yang dilarang dimasuki siapapun lalu ia membuka pintu sebuah kamar tak bernomor di sana. Ternyata kamar itu adalah “Panggonan Wingit”, sebuah tempat yang sudah lama dihuni oleh sosok gaib. Jika ada yang membuka kamar itu, ia akan melihat sosok wanita berkulit putih dan berambut putih yang mengatakan “Telung dino, tengah wengi” yang artinya “Tiga hari, tengah malam”, lalu tiga hari kemudian akan mati dikuliti saat tengah malam. Sekarang nyawa Raina terancam. Ia bersama ARDO (Christian Sugiono) – mantan pacarnya yang seorang jurnalis – Fey, Suktini, dan Garinto mencari cara supaya bisa selamat. Misteri demi misteri yang penuh teka-teki masa lalu terkuak. Akankah mereka bisa selamat dari kematian? Waktu mereka sangat sempit."),
        FilmTicket(11, R.drawable.img_11, "Siksa Neraka", 50000, "Empat kakak beradik, Saleh (Rizky Fachrel), Fajar (Kiesha Alvaro), Tyas (Ratu Sofya), dan Azizah (Nayla Purnama), sejak kecil telah mendengar kisah-kisah mengenai surga dan neraka. Mereka dididik dengan keras oleh bapak (Ariyo Wahab) mereka, seorang ustad muda yang terpandang di desa. Suatu malam, dalam perjalanan menuju desa seberang tanpa sepengetahuan orang tua mereka, Saleh dan adik-adiknya terseret arus sungai yang deras dan menghilang. Saleh kemudian terbangun di alam yang lain, neraka yang selalu dikisahkan bapaknya. Pencarian dilakukan di dunia untuk menemukan anak-anak bapak, entah hidup atau mati. Satu per satu rahasia terungkap, membuat bapak dan ibu (Astri Nurdin) mempertanyakan apakah mereka sudah cukup membekali anak-anaknya. Di neraka, Saleh dan yang lain juga saling mencari, sambil menghadapi siksaan yang kian besar atas dosa-dosa yang selama ini mereka sembunyikan."),
        FilmTicket(12, R.drawable.img_7, "Sijjin", 50000, "Irma (Anggika Bolsterli) jatuh cinta pada Galang (Ibrahim Risyad), sepupunya yang sudah beristri dan punya anak. Namun Irma masih terobsesi dan ingin menjadi perempuan satu-satunya di hidup Galang. Irma datang ke dukun untuk mengirim santet pada istri Galang. Sejak saat itu teror dimulai. Gangguan mistis, kesurupan, dan kematian terjadi di rumah Galang. Namun, yang tak diduga Irma, ancaman itu juga mengincar nyawanya sendiri."),
    )
}